;do $System.OBJ.LoadDir("/opt/irisapp/src","ck",,1)

zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")
;zn "%SYS" d ##class(Security.SSLConfigs).Create("z") s r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="z" d r.Get("/packages/zpm/latest/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")
zn "USER"
zpm "install csvgen"
zpm "install fileserver"
zpm "load /opt/irisapp/ -v":1:1
halt
